
#define ID_ICONEXECUTABLE               5
#define IDD_PACKULONG_FLAGS             9
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_PACKSTRING                  101
#define IDD_FORMVIEWBASEOBJECT          103
#define IDD_DIALOG_ABSTRACTPACKSERIALIZABLE 104
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDR_VedaDemoOGLMfcGTYPE         129
#define IDR_MENU_CLASSNODE              129
#define IDD_PACKULONG                   129
#define IDB_TREEIMAGELIST               130
#define IDD_PACKREFERENCE               130
#define IDR_MENU_BASEOBJECT             131
#define IDD_PackListDynamic             131
#define IDB_TREEIMAGELIST1              131
#define IDD_PACKLONG_WITHLIMITS         132
#define IDR_MENU_CLASSNODE1             132
#define IDR_MENU_CCLASSNODE             132
#define IDD_PACKLONG                    133
#define IDD_FORMVIEWPREVIEW             134
#define IDI_ICON1                       134
#define IDD_FORMVIEWBASEOBJECT1         135
#define IDD_PackStruct                  135
#define IDD_PACKTREECELL                136
#define IDD_PACKSERIALIZABLE            137
#define IDD_PACKULONG_ENUMS             138
#define IDD_PACKFLOAT                   139
#define IDD_PACKFLOAT_WITHLIMITS        140
#define IDD_PackFloatByte_Limits        140
#define IDD_PACKULONG_ENUMS1            141
#define IDD_PACKDYNAMICTYPE             141
#define IDD_PACKRESOURCE                142
#define IDD_PACKSTRING1                 143
#define IDD_PACKSTRINGMULTIPLE          143
#define IDD_DIALOG1                     144
#define IDC_EDIT1                       1001
#define IDC_EDIT2                       1002
#define IDC_LIST1                       1003
#define IDC_EDIT3                       1003
#define IDC_StringCtrl                  1004
#define IDC_EDIT4                       1004
#define IDC_SCROLLBAR1                  1005
#define IDC_CHECK1                      1006
#define IDC_SLIDER1                     1007
#define IDC_SelectedName                1008
#define IDC_OBJECTCOMBO                 1009
#define IDC_CHECK2                      1010
#define IDC_BUTTON_PLUS                 1010
#define IDC_SelectedName2               1010
#define IDC_PREVIEW                     1010
#define IDC_CHECK3                      1011
#define IDC_BUTTON_PLUS2                1011
#define IDC_STATICMIN                   1011
#define IDC_OBJECTCOMBO2                1011
#define IDC_NEWCOMBO                    1011
#define IDC_CHECK4                      1012
#define IDC_STATICMIN2                  1012
#define IDC_STATICMAX                   1012
#define IDC_CLASSINFO                   1012
#define IDC_CHECK5                      1013
#define IDC_CLASSINFO2                  1013
#define IDC_OBJECTOUTPUT                1013
#define IDC_STATICMIN22                 1013
#define IDC_CHECK6                      1014
#define IDC_STATICMAX2                  1014
#define IDC_SPIN1                       1015
#define IDC_CHECK7                      1015
#define IDC_STATICMIN3                  1015
#define IDC_BUTTON1                     1016
#define IDC_B_RETURNSTOP                1016
#define IDC_CHECK8                      1016
#define IDC_STATICMAX3                  1016
#define IDC_FILEPROP                    1016
#define IDC_BUTTON2                     1017
#define IDC_TREE1                       1017
#define IDC_B_PLAYPAUSE                 1017
#define IDC_B_PLAY                      1017
#define IDC_CHECK9                      1017
#define IDC_STATICMAX4                  1017
#define IDC_BUTTON3                     1018
#define IDC_RESETVP                     1018
#define IDC_B_RESETVP                   1018
#define IDC_CHECK10                     1018
#define IDC_TOOLFUNCBT2                 1018
#define IDC_B_t                         1019
#define IDC_BRETURNSTOP                 1019
#define IDC_B_PAUSE                     1019
#define IDC_BUTTON_MINUS                1020
#define IDC_BPLAYPAUSE                  1020
#define IDC_B_VPZOOMIN                  1020
#define IDC_TOOLFUNCBT3                 1020
#define IDC_PREVIEWOB                   1021
#define IDC_BRESETLAYOUT                1021
#define IDC_B_VPZOOMOUT                 1021
#define IDC_B_ROTATEPREVIEW             1021
#define IDC_BUTTON_UP                   1021
#define IDC_MINSEC                      1022
#define IDC_B_VPZOOMOUT1                1022
#define IDC_B_VPSCROLL                  1022
#define IDC_TOOLFUNCBT1                 1022
#define IDC_B_MOVEPREVIEW               1022
#define IDC_BUTTON_DOWN                 1022
#define IDC_MAXSEC                      1023
#define IDC_TOOLFUNCBT4                 1023
#define IDC_B_RESETVP1                  1023
#define IDC_B_RESETVPFOCUS              1023
#define IDC_BUTTON_Clone                1023
#define IDC_BZOOMIN                     1024
#define IDC_TOOLFUNCBT5                 1024
#define IDC_B_VPZOOMINFOCUS             1024
#define IDC_BUTTON_SELECTATPTIME        1024
#define IDC_BZOOMOUT                    1025
#define IDC_B_VPZOOMOUTFOCUS            1025
#define IDC_B_ROTATEPREVIEWFOCUS        1025
#define IDC_BZOOM                       1025
#define IDC_BUTTON_SELECTATPTIME2       1025
#define IDC_BUTTON_ADDATPTIME           1025
#define IDC_BSCROLL                     1026
#define IDC_B_VPSCROLL1                 1026
#define IDC_B_VPSCROLLFOCUS             1026
#define IDC_B_MOVEPREVIEWFOCUS          1026
#define IDC_BMOVE                       1026
#define IDC_PLAYSPEED                   1027
#define IDC_B_VPRESET                   1027
#define IDC_BSCROLL2                    1027
#define IDC_BROTATE                     1027
#define IDC_OBJECTNAME                  1028
#define IDC_B_VPRESETFOCUS              1028
#define IDC_SLIDER2                     1029
#define IDC_SLIDERSOUND                 1029
#define IDC_B_PLAY1                     1029
#define IDC_B_FILEOPEN                  1029
#define IDC_SLIDERTIME                  1030
#define IDC_SLIDER3                     1030
#define IDC_SLIDERTIME2                 1031
#define IDC_CUSTOM1                     1031
#define IDC_SLIDERSPEED                 1031
#define IDC_SLIDER4                     1031
#define IDC_LISTMEMBEREDITOR            1032
#define IDC_COMBO1                      1033
#define IDC_COMBOENUMS                  1033
#define IDC_STATICX                     1034
#define IDC_STATICY                     1035
#define IDC_STATICZ                     1036
#define IDC_STATICZ2                    1037
#define IDC_STATICD                     1037
#define IDC_BEDIT_XYZ                   1038
#define IDC_Speed                       1039
#define IDC_BEDIT_X                     1040
#define IDC_DATE                        1040
#define IDC_BEDIT_XYZ2                  1041
#define IDC_BEDIT_XY                    1041
#define IDC_DATE2                       1041
#define IDC_CREATEOB                    1042
#define IDC_PROGRESS1                   1043
#define IDC_PROGRESSCONSTRUCT           1043
#define IDC_MEMBERNAME                  1044
#define IDC_SCROLLBAR2                  1046
#define IDC_EDITDLG1                    1050
#define IDC_ABOUT_VERSION               1051
#define ID_CREATE_DESTROY               32771
#define ID_BASEOBJECT_CLONE             32772
#define ID_BASEOBJECT_DESTROY           32773
#define ID_NEWOBJECT                    32775
#define ID_UNDO                         32777
#define ID_REDO                         32778
#define ID_BUTTON32780                  32780
#define ID_FLUSHNAMES                   32780
#define ID_MERGE                        32781
#define ID_BASEOBJECT_DESTROYINDEPENDANT 32782
#define ID_MPREVIEW                     32784
#define ID_Menu                         32785
#define ID_FILE_EMPTYCONTEXT            32787
#define ID_FILE_LIBIMAGE                32789
#define ID_FILE_LIBBAOOM                32791
#define ID_FILE_LIBDEMO                 32793
#define ID_Menu32794                    32794
#define ID_MPREVIEWB1                   32796
#define ID_Menu32798                    32798
#define ID_MEDITB1                      32801
#define ID_MEDITPreview                 32802
#define ID_EXPORTCFILE                  32805
#define ID_EXPORTEXEC                   32806
#define ID_EXPORTEXECUTABLE             32809
#define ID_Menu32810                    32810
#define ID_Menu32811                    32811
#define ID_FORCELANGUAGE_ENGLISH        32813
#define ID_FORCEPREVIEWLANGUAGE_FRENCH  32814
#define ID_FORCEPREVIEWLANGUAGE_SPANISH 32815
#define ID_FORCEPREVIEWLANGUAGE_GERMAN  32816
#define ID_FORCEPREVIEWLANGUAGE_ITALIAN 32817
#define ID_FORCEPREVIEWLANGUAGE_POLISH  32818
#define ID_FORCEPREVIEWLANGUAGE_PORTU   32819
#define ID_Menu32820                    32820

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32821
#define _APS_NEXT_CONTROL_VALUE         1052
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
